#!/bin/bash -l

#SBATCH --partition=mpi

#SBATCH --cpus-per-task=1
#SBATCH --nodes=10
#SBATCh --ntasks-per-node=8
#SBATCH --ntasks=75
#SBATCH --mem=22gb

#SBATCH --time=24:00:00
#SBATCH --account=AGWalch

#SBATCH --mail-user=jmarker2@uni-koeln.de
#SBATCH --mail-type=all

module load hdf5
module load intel
module load intelmpi

FLASH_EXE="$1"
FLASH_PAR="$2"

srun -n "$SLURM_NTASKS" "$FLASH_EXE" -par_file "$FLASH_PAR"
