#!/bin/bash -l

#SBATCH --partition=mpi

#SBATCH --cpus-per-task=1
#SBATCH --nodes=10
#SBATCh --ntasks-per-node=8
#SBATCH --ntasks=75
#SBATCH --mem=22gb

#SBATCH --time=05:00:00
#SBATCH --account=AGWalch

#SBATCH --mail-user=jmarker2@uni-koeln.de
#SBATCH --mail-type=all

"$@" "$SLURM_NTASKS"
