#!/bin/sh

if hostname | grep -qE '^cheops'
then
    module purge
    module load hdf5/1.8.13     2> /dev/null
    module load openmpi         2> /dev/null
    module load python/3.4.3    2> /dev/null
fi

export TURBUBOX_ROOT="$HOME/turbubox"
export PYTHONPATH="$PYTHONPATH:$TURBUBOX_ROOT/tools/bin:$TURBUBOX_ROOT/tools/lib"

/usr/bin/env python3 "$@"
