#!/bin/sh

set -e # exit on error

if hostname | grep -qE 'jmark'
then
    export TURBUBOX_ROOT="$HOME/projects/turbubox"
    export PYTHONPATH="$PYTHONPATH:$TURBUBOX_ROOT/tools/bin:$TURBUBOX_ROOT/tools/lib"

elif hostname | grep -qE '^cheops'
then
    module purge
    module load hdf5/1.8.13     2> /dev/null
    module load openmpi         2> /dev/null
    module load python/3.4.3    2> /dev/null

    export TURBUBOX_ROOT="$HOME/turbubox"
    export PYTHONPATH="$PYTHONPATH:$TURBUBOX_ROOT/tools/bin:$TURBUBOX_ROOT/tools/lib"

elif hostname -f | grep -qE 'login[0-9]+(\.sm\.lrz\.de)?' # SuperMUC
then
    source /etc/profile.d/modules.sh

    module load python/3.5_intel > /dev/null || echo "loading python3 failed"
    module load hdf5/serial/1.8.15 > /dev/null || echo "loading hdf5/serial failed"

    export TURBUBOX_ROOT="$HOME/turbubox"
    export PYTHONPATH="$PYTHONPATH:$TURBUBOX_ROOT/tools/bin:$TURBUBOX_ROOT/tools/lib"
fi

/usr/bin/env python3 "$@"
